백엔드/coplate/urls.py
from django.urls import path

from . import views
from django.views.generic import RedirectView
from django.urls import reverse_lazy
urlpatterns = [

    # # login
    # path('', RedirectView.as_view(url=reverse_lazy('account_login'), permanent=False)), # 처음 페이지를 로그인 화면으로 바꾸기 
    # # review
    # path('index', views.IndexView.as_view(), name='index'),
    # path('style_cafe/', views.Style_CafeListView.as_view(), name='style-cafe-list'),
    # path('style_cafe/<int:cafe_id>/', views.CafeDetailView.as_view(), name='style-cafe-detail'),
    # # path('style_cafee/<int:cafe_id>/', views.CafeDetailView.as_view(), name='cafe-detail'),
    # path('cafes/<int:pk>/', views.CafeDetailView.as_view(), name='cafe-detail'),
    # path('cafes/<int:pk>/delete/', views.CafeDeleteView.as_view(), name='cafe-delete'),

    # path('cafes/', views.CafeListView.as_view(), name='cafe-list'),
    # path('cafes/<int:pk>/update/', views.CafeUpdateView.as_view(), name='cafe-update'),

    # path('style_cafe/new/', views.CafeCreateView.as_view(), name='cafe-create'),
    # path('style_cafe/<int:review_id>/edit/', views.CafeUpdateView.as_view(), name='style-cafe-update'),
    # path('style_search/',views.SearchView.as_view(), name='search'),
    # path('style_cafe/<int:pk>/delete/', views.CafeDeleteView.as_view(), name='style-cafe-delete'),
    # path('style_cafe/following/', views.FollowingReviewListView.as_view(), name='style-following-review-list'),
   
    # # profile
    # path('users/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    # path('users/<int:user_id>/reviews/', views.UserReviewListView.as_view(), name='user-review-list'),
    # path('set-profile/', views.ProfileSetView.as_view(), name='profile-set'),
    # path('edit-profile/', views.ProfileUpdateView.as_view(), name='profile-update'),

     path('', RedirectView.as_view(url=reverse_lazy('account_login'), permanent=False)), # 로그인 페이지로 리디렉션
    path('image_upload/', views.ImageUploadView.as_view(), name='image-upload'),  # 이미지 업로드 페이지
    path('result/', views.ClassificationResultView.as_view(), name='classification-result'),
    # cafe
    path('index/', views.IndexView.as_view(), name='index'),
    path('cafes/', views.CafeListView.as_view(), name='cafe-list'),
    path('cafes/<int:pk>/', views.CafeDetailView.as_view(), name='cafe-detail'),
    path('cafes/<int:pk>/update/', views.CafeUpdateView.as_view(), name='cafe-update'),
    path('cafes/<int:pk>/delete/', views.CafeDeleteView.as_view(), name='cafe-delete'),
    
    # style cafe
    path('style_cafe/', views.Style_CafeListView.as_view(), name='style-cafe-list'),
    path('style_cafe/new/', views.CafeCreateView.as_view(), name='cafe-create'),
    path('style_cafe/<int:pk>/', views.CafeDetailView.as_view(), name='style-cafe-detail'),
    path('style_cafe/<int:pk>/edit/', views.CafeUpdateView.as_view(), name='style-cafe-update'),
    path('style_cafe/<int:pk>/delete/', views.CafeDeleteView.as_view(), name='style-cafe-delete'),
    path('style_search/', views.SearchView.as_view(), name='search'),
    path('style_cafe/following/', views.FollowingReviewListView.as_view(), name='style-following-review-list'),

    # profile
    path('users/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('users/<int:user_id>/reviews/', views.UserReviewListView.as_view(), name='user-review-list'),
    path('set-profile/', views.ProfileSetView.as_view(), name='profile-set'),
    path('edit-profile/', views.ProfileUpdateView.as_view(), name='profile-update'),


     path('users/<int:pk>/liked-cafes/', views.LikedCafeListView.as_view(), name='liked-cafe-list'),
    path('users/<int:pk>/liked-dripshots/', views.LikedDripshotListView.as_view(), name='liked-dripshot-list'),


    # dripshot
   # path('dripshot/',views.DripshotListView.as_view(),name='dripshot-list'),
   # path('dripshot/list/',views.DripshotMainListView.as_view(),name='dripshot-main-list'), # 여기까지 만듬 
   # path('cafes/<int:cafe_id>/', views.DripshotDetailView.as_view(), name='dripshot-detail'),
   # path('cafes/new/', views.DripshotCreateView.as_view(), name='dripshot-create'),
   # path('cafes/<int:review_id>/edit/', views.DripshotUpdateView.as_view(), name='dripshot-update'),
   # path('cafes/<int:cafe_id>/delete/', views.DripshotDeleteView.as_view(), name='dripshot-delete'),
   # path('cafes/following/', views.FollowingReviewListView.as_view(), name='following-review-list'),
    path('dripshot/', views.DripshotListView.as_view(), name='dripshot-list'),
    path('dripshot/list/', views.DripshotMainListView.as_view(), name='dripshot-main-list'),
    path('dripshot/<int:pk>/', views.DripshotDetailView.as_view(), name='dripshot-detail'),
    path('dripshot/new/', views.DripshotCreateView.as_view(), name='dripshot-create'),
    path('dripshot/<int:pk>/edit/', views.DripshotUpdateView.as_view(), name='dripshot-update'),
    path('dripshot/<int:pk>/delete/', views.DripshotDeleteView.as_view(), name='dripshot-delete'),
    # around 
    path('around/',views.CafeAroundListView.as_view(),name='around-list'), 
    path('around/list',views.CafeAroundMainListView.as_view(),name='around-main-list'),
    # path('cafes/<int:cafe_id>/', views.ReviewDetailView.as_view(), name='around-detail'),
    # path('cafes/new/', views.ReviewCreateView.as_view(), name='around-create'),
    # path('cafes/<int:review_id>/edit/', views.ReviewUpdateView.as_view(), name='around-update'),
    # path('cafes/<int:cafe_id>/delete/', views.ReviewDeleteView.as_view(), name='around-delete'),
    path('cafes/following/', views.FollowingReviewListView.as_view(), name='following-review-list'),

    #js
    path('cafe-autocomplete/', views.CafeAutocomplete.as_view(), name='cafe-autocomplete'),


    # comment
   path(
    'cafes/<int:pk>/comments/create/',
    views.CommentCreateView.as_view(),
    name='comment-create',
),
    path('cafes/comments/<int:pk>/edit/', 
     views.CommentUpdateView.as_view(), 
     name='comment-update'),
    path('cafes/comments/<int:pk>/delete/', 
     views.CommentDeleteView.as_view(), 
     name='comment-delete'),
    path('dripshots/<int:pk>/comments/create/', views.DripshotCommentCreateView.as_view(), name='dripshot-comment-create'),

    # like
    path(
        'like/<int:content_type_id>/<int:object_id>/', # 이미 그 좋아요에는 contetn_type 이 이미 있는거임 
        views.ProcessLikeView.as_view(),
        name='process-like'
    ),
    # follow
    path(
        'users/<int:pk>/follow/',
        views.ProcessFollowView.as_view(),
        name='process-follow',
    ),
    path('users/<int:pk>/following/', 
         views.FollowingListView.as_view(),
           name='following-list'),
    path('users/<int:pk>/followers/', 
         views.FollowerListView.as_view(),
           name='follower-list'),


]

백엔드/coplate_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from coplate.views import CustomPasswordChangeView

urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # coplate
    path('', include('coplate.urls')),
    # allauth
    path(
        'email-confirmation-required/',
        TemplateView.as_view(template_name='account/email_confirmation_required.html'),
        name='account_email_confirmation_required',
    ),
    path(
        'email-confirmation-done/',
        TemplateView.as_view(template_name='account/email_confirmation_done.html'),
        name='account_email_confirmation_done',
    ),
    path('password/change/', CustomPasswordChangeView.as_view(), name='account_change_password'),
    path('', include('allauth.urls')),
    
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

백엔드/coplate/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
import os

def cafe_pic_upload_to(instance, filename):
    new_filename = filename.replace(" ", "_")
    return f'cafe_images/{instance.id}_{instance.name}_images/{new_filename}'

def dripshot_pic_upload_to(instance, filename):
    return f'user_pic/{filename}'

def person_pic_upload_to(instance, filename):
    return f'person/{filename}'

def cafe_image_upload_to(instance, filename):
    # 카페 이름을 포함한 폴더에 이미지를 저장
    folder_name = f"{instance.id}_{instance.name}_images"
    return os.path.join('cafe_images', folder_name, filename)

class StyleKeyword(models.Model):
    keyword = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.keyword

# class CafeKeyword(models.Model):
#     name = models.CharField(max_length=100, unique=True)

#     def __str__(self):
#         return self.name
def person_pic_upload_to(instance, filename):
    # 파일이 저장될 경로를 정의
    return f'user_pics/{filename}'


class User(AbstractUser):
    name = models.CharField(max_length=15, null=False, default='Unknown', error_messages={"null": "이름을 입력해주세요."})
    profile_pic = models.FileField(upload_to='profile_pics', default='default_profile_pic.jpg')
    GENDER_CHOICES = [
        (1, "남자"),
        (2, "여자")
    ]
    birth_date = models.DateField(null=True, blank=True, error_messages={"null": "생년월일을 입력해주세요."})
    gender = models.IntegerField(choices=GENDER_CHOICES, default=1)
    recommend_location = models.CharField(max_length=100, error_messages={"null": "존재하지 않는 역입니다."})
    following = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='followers')
    style_keywords = models.ManyToManyField(StyleKeyword, related_name='users', blank=True)
    uploaded_image = models.ImageField(upload_to='uploaded_images/', null=True, blank=True)
    classification_result = models.JSONField(null=True, blank=True)  # 분류 결과를 JSON 형식으로 저장
    def __str__(self):
        return self.email

class Cafe(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    address_url = models.URLField(null=True)
    total_review = models.IntegerField(null=True)
    sns_link = models.URLField(null=True)
    image1 = models.ImageField(upload_to=cafe_image_upload_to, blank=True)
    image2 = models.ImageField(upload_to=cafe_image_upload_to, blank=True)
    image3 = models.ImageField(upload_to=cafe_image_upload_to, blank=True)
    image4 = models.ImageField(upload_to=cafe_image_upload_to, blank=True)
    image5 = models.ImageField(upload_to=cafe_image_upload_to, blank=True)
    rating = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    short_description = models.CharField(max_length=500)
    content = models.TextField(max_length=500, blank=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cafes')
    likes = GenericRelation('Like', related_query_name='dripshot')
    style_keywords = models.ManyToManyField(StyleKeyword, blank=True, related_name='cafes')  # Added this line
    comments = GenericRelation('Comment', related_query_name='cafes')

    def __str__(self):
        return self.name


class Dripshot(models.Model):
    title = models.CharField(max_length=50)
    image1 = models.FileField(upload_to=dripshot_pic_upload_to, blank=False)
    image1_url = models.URLField(blank=False)
    image2 = models.FileField(upload_to=dripshot_pic_upload_to, blank=True)
    image2_url = models.URLField(blank=True)
    image3 = models.FileField(upload_to=dripshot_pic_upload_to, blank=True)
    image3_url = models.URLField(blank=True)
    image4 = models.FileField(upload_to=dripshot_pic_upload_to, blank=True)
    image4_url = models.URLField(blank=True)
    image5 = models.FileField(upload_to=dripshot_pic_upload_to, blank=True)
    image5_url = models.URLField(blank=True)
    dt_created = models.DateTimeField(auto_now_add=True)
    dt_updated = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=500, blank=False)
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE, related_name='dripshots', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dripshot')
    likes = GenericRelation('Like', related_query_name='dripshot')
    RATING_CHOICES = [
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    ]
    rating = models.IntegerField(choices=RATING_CHOICES, default=None, null=True, blank=True)
    comments = GenericRelation('Comment', related_query_name='cafes')

    def __str__(self):
        return self.title 

class Like(models.Model):
    dt_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    liked_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return f"({self.user}, {self.liked_object})"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'content_type', 'object_id'], name='unique_like')
        ]

class Comment(models.Model):
    content = models.TextField(max_length=500, blank=False)
    dt_created = models.DateTimeField(auto_now_add=True)
    dt_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    likes = GenericRelation('Like', related_query_name='comments')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.content[:30]

    class Meta:
        ordering = ['-dt_created']

백엔드/coplate/forms.py
from django import forms

from .models import *


class DripshotForm(forms.ModelForm):
    cafe = forms.ModelChoiceField(
        queryset=Cafe.objects.all(),
        label='카페를 선택하세요',
        widget=forms.Select(attrs={'class': 'select2'})  # select2 클래스를 추가하여 Select2를 적용
    )

    class Meta:
        model = Dripshot
        fields = [
            'title',
            'image1',
            'image2',
            'image3',
            'image4',
            'image5',
            'content',
            'cafe',
            'rating',
        ]
        widgets = {
            'rating': forms.Select(),  # Select 위젯을 사용하여 드롭다운으로 선택 가능
        }

    

class CafeForm(forms.ModelForm): # 카페 추가 창 만들때 사용하는거
    class Meta:
        model = Cafe
        fields = [
            'name',
            'address',
            'address_url',
            'sns_link',
            'image1',
            'image2',
            'image3',
            'image4',
            'image5',
        
            'content',
        ]
#class ProfileForm(forms.ModelForm):
 #   class Meta:
  #      model = User
   #     fields = [
    #        'name',
     #       'gender',
      #      'birth_date',
       #     'recommend_location',
        #    'profile_pic',
         #   'style_keywords',
      #  ]
       # widgets = {
        #    'style_keywords': forms.CheckboxSelectMultiple(),  # 체크박스 위젯으로 설정
         #   'birth_date': forms.DateInput(attrs={'type': 'date'}),
       # }
class ProfileForm(forms.ModelForm):
    style_keywords = forms.ModelMultipleChoiceField(
        queryset=StyleKeyword.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = User
        fields = ['name', 'profile_pic','birth_date','recommend_location', 'style_keywords']
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     # 첫 3개의 스타일 키워드만 선택 가능하도록 제한
    #     self.fields['style_keywords'].queryset = StyleKeyword.objects.all()[:12]

class CafeEssentialForm(forms.ModelForm):
    class Meta:
        model = Cafe
        fields = ['name', 'short_description', 'content', 'author']     
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': forms.Textarea,
        }
class ImageUploadForm(forms.Form):
    image = forms.ImageField(label='Upload an image')

백엔드/coplate/templates/coplate/around_list.html
{% extends "coplate_base/base_with_navbar.html" %}

{% block title %}리뷰 목록 ({{ paginator.count }}) | Coplate{% endblock title %}

{% block content %}
<main class="site-body">
  <div class="content-list max-content-width">
    <div class="header">
      <h2>내 주변 카페</h2>
    </div>
    {% include "components/around_main_list.html" with cafes=cafes empty_message="아직 리뷰가 없어요:(" %}
   
    {% if is_paginated %}
      {% include 'components/pagination.html' with page_obj=page_obj %}
    {% endif %}
  </div>
</main>
{% endblock content %}

백엔드/coplate/templates/coplate/cafe_detail.html
{% extends "coplate_base/base_with_navbar.html" %}

{% load static %}
{% load widget_tweaks %}
{% load custom_filters %}

{% block title %}{{ cafe.name }} | Drip-Shot{% endblock title %}

{% block content %}
<main class="site-body">
  <article class="review-detail max-content-width">
    <!-- 카페 정보 표시 -->
    <div class="review-info">
      <div class="restaurant-name">
        <span class="cp-chip green">{{ cafe.name }}</span>
      </div>
      <h1 class="title">{{ cafe.title }}</h1>
      <a class="review-author" href="{% url 'profile' cafe.author.id %}">
        <div class="author">
          <!-- 작성자 정보 표시 -->
        </div>
      </a>
      <date class="date">{{ cafe.dt_created|date:"Y년 n월 j일" }}</date>
    </div>

    <!-- 이미지 캐러셀 -->
    <div class="content">
      <div class="carousel">
        <div class="images">
          <img class="full" src="{{ cafe.image1.url }}">
          {% if cafe.image2 %}
            <img class="full hidden" src="{{ cafe.image2.url }}">
          {% endif %}
          {% if cafe.image3 %}
            <img class="full hidden" src="{{ cafe.image3.url }}">
          {% endif %}
          {% if cafe.image4 %}
            <img class="full hidden" src="{{ cafe.image4.url }}">
          {% endif %}
          {% if cafe.image5 %}
            <img class="full hidden" src="{{ cafe.image5.url }}">
          {% endif %}
          <img class="carousel-button prev" src="{% static 'coplate/icons/ic-prev.svg' %}">
          <img class="carousel-button next" src="{% static 'coplate/icons/ic-next.svg' %}">
        </div>
      </div>
    </div>

    <!-- 평점 및 카페 설명 -->
    <div class="rating">
      {% if cafe.rating is not None %}
        {{ cafe.rating|star_rating }}
      {% else %}
        No rating available
      {% endif %}
    </div>
    <p class="content">{{ cafe.content|linebreaksbr }}</p>
    <a class="location" target="_blank" href="{{ cafe.address_url }}">
      <img class="cp-icon" src="{% static 'coplate/icons/ic-pin.svg' %}" alt="Pin Icon">
      <span>위치보기</span>
    </a>

    <!-- Dripshots 표시 -->
    <div class="dripshots-section">
      <h2>Dripshots</h2>
      <div class="dripshots-list">
        {% for dripshot in cafe.dripshots.all %}
          <a href="{% url 'dripshot-detail' dripshot.pk %}">
            <section class="cp-card dripshot-content">
              <!-- 이미지가 있는 경우에만 배경 이미지로 설정 -->
              {% if dripshot.image1 %}
                <div class="thumb" style="background-image: url('{{ dripshot.image1.url }}');"></div>
              {% else %}
                <div class="thumb"></div> <!-- 이미지가 없을 경우 빈 div 또는 기본 배경 -->
              {% endif %}
    
              <div class="body">
                <!-- Dripshot 제목 -->
                <h3 class="title">{{ dripshot.title }}</h3>
    
                <!-- Dripshot 내용 -->
                <p class="content">{{ dripshot.content|truncatewords:15 }}</p>
                <div class="rating">
                  {% if dripshot.rating is not None %}
                    {{ dripshot.rating|star_rating }}
                  {% else %}
                    No rating available
                  {% endif %}
                </div>
                <div class="author-info">
                  <div class="author-avatar" style="background-image: url('{{ dripshot.author.profile_pic.url }}');"></div>
                  <p class="author-name">{{ dripshot.author.name }}</p>
                </div>
              </div>
            </section>
          </a>
        {% endfor %}
      </div>
    </div>

    <!-- 좋아요 및 댓글 섹션 -->
    <div class="like-comment-block">
      <div class="like-comment-header">
        <form action='{% url "process-like" cafe_ctype_id cafe.pk %}' method='post'>
          {% csrf_token %}
          <button class="like-button" type="submit" data-login-required>
            {% if likes_cafe %}
              <img width="21px" src="{% static 'coplate/icons/ic-heart-orange.svg' %}" alt="filled like icon">
            {% else %}
              <img width="21px" src="{% static 'coplate/icons/ic-heart.svg' %}" alt="like icon">
            {%endif%}
            <span> 좋아요 {{cafe.likes.count}}</span>
          </button>
        </form>
        <div class="comment-info">
          <img src="{% static 'coplate/icons/ic-comment.svg' %}" alt="comment icon">
          <span> 댓글 {{cafe.comments.count}}</span>
        </div>
      </div>
      
      <!-- 댓글 작성 섹션 -->
      <form class="comment-create-form" action="{% url 'comment-create' cafe.pk %}" method="post">
        {% csrf_token %}
        {% if user.is_authenticated %}
          {{ form.content|attr:"placeholder:댓글 내용을 입력해주세요."|add_class:"cp-input" }}
          <button class="cp-button small" type="submit">등록</button>
        {% else %} 
          <a href="{% url 'account_login' %}?next={% url 'cafe-detail' cafe.pk %}">
            {{ form.content|attr:"placeholder:댓글을 작성하려면 로그인이 필요합니다."|add_class:"cp-input"|attr:"disabled" }}
          </a>
          <button class="cp-button small secondary" type="submit" disabled>등록</button>
        {% endif %}
      </form>

      <!-- 댓글 목록 -->
      <div class="comment-list">
        {% for comment in cafe.comments.all %}
          <div class="comment">
            <div class="comment-header">
              <a href="{% url 'profile' comment.author.id %}">
                <div class="author">
                  <div class="cp-avatar" style="background-image: url('{{ comment.author.profile_pic.url }}')"></div>
                  <span>{{ comment.author.name }}</span>
                </div>
              </a>
              {% if user == comment.author %}
                <div class="buttons">
                  <a href="{% url "comment-delete" comment.pk %}">삭제</a>
                  <span> | </span>
                  <a href="{% url "comment-update" comment.pk %}">수정</a>
                </div>
              {% endif %}
            </div>
            <div class="comment-content">
              {{ comment.content|linebreaksbr }}
            </div>
            <div class="comment-footer">
              <div class="comment-date">
                {{ comment.dt_created|date:"Y년 n월 j일" }}
              </div>
                <form action='{% url "process-like" comment_ctype_id comment.pk %}' method='post'>
                  {% csrf_token %}
                  <button class="like-button" type="submit" data-login-required>
                    {% if comment in liked_comments %}
                      <img width="21px" src="{% static 'coplate/icons/ic-heart-orange.svg' %}" alt="like icon">
                    {% else %}
                      <img width="21px" src="{% static 'coplate/icons/ic-heart.svg' %}" alt="like icon">
                    {%endif%}
                    <span> 좋아요 {{comment.likes.count}}</span>
                  </button>
                </form>
                
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <!-- 카페 수정 및 삭제 버튼 -->
    {% if cafe.author == user %}
      <div class="footer">
        <div class="buttons">
          <a class="cp-button warn" href="{% url 'cafe-delete' cafe.pk %}">삭제</a>
          <a class="cp-button secondary" href="{% url 'cafe-update' cafe.pk %}">수정</a>
        </div>
      </div>
    {% endif %}
  </article>
</main>
{% endblock content %}
{% block js %}
<script>
  const isAuthenticated = '{{user.is_authenticated}}' === 'True';
</script>
<script src="{% static 'coplate/js/auth.js' %}"></script>
<script src="{% static 'coplate/js/carousel.js' %}"></script>

{% endblock js %}

백엔드/coplate/templates/coplate/caffe_confirm_delete.html
{% extends "coplate_base/base_with_navbar.html" %}

{% block title %}{{ caffe.name }} | Drip-Shot{% endblock title %}

{% block content %}
<main class="site-body">
  <form class="cp-dialog confirm-delete" method="post">
    {% csrf_token %}
    <span class="content">정말 카페 정보를 삭제하시겠습니까?</span>
    <button class="cp-button warn" type="submit">삭제</button>
    <a class="cp-button secondary" href="{% url 'caffe-detail' caffe.id %}">취소</a>
  </form>
</main>
{% endblock content %}

백엔드/coplate/templates/coplate/caffe_list.html
{% extends "coplate_base/base_with_navbar.html" %}

{% block title %}리뷰 목록 ({{ paginator.count }}) | Drip-Shot{% endblock title %}

{% block content %}
<main class="site-body">
  <div class="content-list max-content-width">
    <div class="header">
      <h2>리뷰 목록</h2>
    </div>
    {% include "components/caffe_list.html" with caffe=caffe empty_message="아직 리뷰가 없어요:(" %}
   
    {% if is_paginated %}
      {% include 'components/pagination.html' with page_obj=page_obj %}
    {% endif %}
  </div>
</main>
{% endblock content %}

백엔드/coplate/templates/coplate/clothes_list.html
{% extends "coplate_base/base_with_navbar.html" %}

{% block title %}옷 목록 ({{ paginator.count }}) | Coplate{% endblock title %}

{% block content %}
<main class="site-body">
  <div class="content-list max-content-width">
    <div class="header">
      <h2>옷 목록</h2>
    </div>
    {% include "components/clothes_list.html" with reviews=reviews empty_message="아직 옷 리뷰가 없어요:(" %}
   
    {% if is_paginated %}
      {% include 'components/pagination.html' with page_obj=page_obj %}
    {% endif %}
  </div>
</main>
{% endblock content %}

백엔드/coplate/templates/coplate/search_result.html
{% extends "coplate_base/base_with_navbar.html" %}

{% block title %}"{{ query }}" | Coplate{% endblock title %}

{% block content %}
<main class="site-body">
  <div class="content-list max-content-width">
    <form class="search-form" action="{% url 'search' %}" method="get">
      <input class="search-input" name="query" value="{{query}}" type="text" placeholder="식당, 음식 등을 검색해보세요" required>
      <button class="cp-button search-button" type="submit">검색</button>
    </form>
    <div class="header">
      <h2>"{{ query }}"에 대한 겸색 결과 ({{ paginator.count }})</h2>
    </div>
    
    {% include 'components/cafe_list.html' with cafe=search_results empty_message="검색 결과가 없어요 :(" %}
    {% if is_paginated %}
      {% include 'components/pagination.html' with page_obj=page_obj %}
    {% endif %}
  </div>
</main>
{% endblock content %}